### ISSUE TITLE
FG is not recognized in the app

### ISSUE THREAD

**Issue by fliegeroli** [ResetXPDR/MSFS_AutoFPS#1]
Hi. FG is not recognized in the app even though I have the FG mod installed and it is also activated in the sim. What could be the reason? It worked with Atofps 2020 too...but unfortunately not with MSFS2024. It shows: PC DX12 instead of FG
![Autofps](https://github.com/user-attachments/assets/286ec36e-72ea-4c84-a026-068e614cc226)

**Comment by ResetXPDR** [comment]
Can you send me the log file located in %appdata%\MSFS_AutoFPS\log. Thanks.

**Comment by fliegeroli** [comment]
Yes.. :-)

[MSFS_AutoFPS20241217.log](https://github.com/user-attachments/files/18171983/MSFS_AutoFPS20241217.log)

**Comment by ResetXPDR** [comment]
The app is saying you don't have FG enabled in MSFS. Can you send me a screen shot of the MSFS 2024 settings window showing it is enabled.

**Comment by fliegeroli** [comment]
Jou will see, that i have 60 fps and the app said 30 ??
![Autofps_2](https://github.com/user-attachments/assets/ca245058-d2f2-4fcb-b375-71a594ace932)

**Comment by fliegeroli** [comment]
![Autofps_3](https://github.com/user-attachments/assets/689e3229-cd18-40d9-98b3-f0c23f6d7fdd)

**Comment by ResetXPDR** [comment]
That's weird. 

I also noticed the memory offset in the log file has changed since last week, suggesting a newer MSFS version is out. What version is your MSFS showing as? Hit ALT ENTER to go to windowed mode and you will see it. ALT ENTER to switch back to full screen.

**Comment by fliegeroli** [comment]
version 1.2.70

![Autofps_4](https://github.com/user-attachments/assets/8f4cded2-3508-4441-b764-0b84e1e25278)

**Comment by ResetXPDR** [comment]
That's the same version as last week and same as mine and mine detects FG just fine and is also the Steam version. Yours should have worked with the original module offset 0x0A241C60, but yours fails the compat test then goes and finds another offset higher in the wrong place that actually passes the compat test, which is very weird indeed.

Let me think about it some more and perhaps give you another test version to try. In the interim, try running the installer, removing it then run the installer and install again and see if it works this time. You can do this without exiting MSFS but you will need to close AutoFPS down. Let me know how it goes.

**Comment by ResetXPDR** [comment]
Can you also send me your Usercfg.opt file in the %appdata%\Microsoft Flight Simulator 2024 directory.

**Comment by ResetXPDR** [comment]
> Okay. Try it. But I don't have the Steam version, I have the Store version???

This is probably what the issue is. Had you ever had the Steam version installed?

I need to find out why yours is detecting as the Steam version. I'll see what it is looking for and get you to check on your system.

**Comment by ResetXPDR** [comment]
I looked at the code and the reason the app is detecting the Steam version is because the file UserCfg.opt was found in the %appdata%\Microsoft Flight Simulator 2024 directory, which is where the Steam MSFS 2024 version gets installed to. Are you absolutely sure you don't have the Steam version installed, or did in the past?

**Comment by fliegeroli** [comment]
I'm sure I didn't have/didn't have a Steam version. I deleted the directory (it was incomplete...), uninstalled autofps, reinstalled it... it works :-)
![Autofps_5](https://github.com/user-attachments/assets/af43f4d9-987c-46a5-8a77-cb7755eeeb31)

**Comment by ResetXPDR** [comment]
That was it. Very strange that Steam folder and file was there but at least we got it working. Enjoy!

**Comment by fliegeroli** [comment]
Yes, also because it was so incomplete. Well, MSFS2024 still has a lot of bugs.. :-) Thanks again and good night

**Comment by fliegeroli** [comment]
They would all be created on November 19, 2024. That's the date it came out... strange
![Autofps_6](https://github.com/user-attachments/assets/4c9aeea7-9f04-48cf-a4bb-21399ed16deb)
