### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by drforweb** [ResetXPDR/MSFS_AutoFPS#10]
The new version 4.4.1 generates CTD on 2024 as soon as you enter the cockpit. If I close the app before starting the flight everything works, as soon as I reopen it MSFS 2024 crashes permanently.

**Comment by fearlessfrog** [comment]
Can can confirm. For me it seems to just freeze in cockpit rather than CTD, so I have to kill the msfs2024 process. Without the latest release running all is well.

**Comment by maximls** [comment]
Same here. As soon as I start the app MSFS freezes. This is when using the latest version of the app and the latest patch from MSFS that came out on Dec 20.

**Comment by N6112FJ** [comment]
patch for 2024 was also released today.  Tried 4.4.0 and also crashes sim..  bet this is something on the MSFS end.

**Comment by ResetXPDR** [comment]
Can those having this issue attach your app log file here and I'll look into it. It's in %appdata%\MSFS_AutoFPS\log

**Comment by ResetXPDR** [comment]
Also, let me know if you use and have updated FSUIPC in the last day or so, as one user fixed theirs by reinstalling FSUIPC from scratch without the \Community\fsuipc-lvar-module folder.

**Comment by fearlessfrog** [comment]
Here's the log with the last flight freezing the MSFS24 screen (e.g. no keyboard, mouse or controller input - it's frozen). 
I haven't changed/updated FSUIPC recently.
[MSFS_AutoFPS20241220.log](https://github.com/user-attachments/files/18216936/MSFS_AutoFPS20241220.log)

**Comment by ResetXPDR** [comment]
Thanks. I'll take a look at it.

Another thing for everyone experiencing this it to uninstall then reinstall MSFS_AutoFPS and not just install versions over the top of each other. To do so, run the installer (any version) and select the Remove button, then run the installer for 0.4.4.1 and install. Let me know if that makes any difference.

**Comment by N6112FJ** [comment]
can't find log file... going to try re-install.

**Comment by ResetXPDR** [comment]
> can't find log file... going to try re-install.

Uninstall then reinstall as advised above.

**Comment by N6112FJ** [comment]
worked!  Thank you!

**Comment by fearlessfrog** [comment]
Yep, can confirm - an uninstall and an install is now working - thanks!

**Comment by ResetXPDR** [comment]
Awesome! I'll be able to let other users know exactly what to do with this. In fact, I'll keep this issue open so others can easily see it.

I thought I had been pretty thorough on not letting a wrong memory address through, but this update sneaked through all my defences. I will adapt and overcome in a near future update!

**Comment by ResetXPDR** [comment]
Closing this now as users reporting this CTD issue have reduced down to nothing.
