### ISSUE TITLE
Close Button kills the app instead of minimizing it to the task bar. 

### ISSUE THREAD

**Issue by emarcelcom** [ResetXPDR/MSFS_AutoFPS#11]
v0.4.4.1 > Close Button used to hide the app to the task bar now it kills the app instead. Please bring back minimize to task bar feature.

**Comment by ResetXPDR** [comment]
The close button now does what it supposed to do - close the app.

The app does still minimise to the task bar, like it always has. Just click the minimise button.

![image](https://github.com/user-attachments/assets/4ade63fd-b4f3-433c-9173-ec8e16a3fe55)

**Comment by Jmknights93** [comment]
I think he actually means system tray, not task bar. I think the previous method was a lot better than the current way. Keeping the task bar clean is a must in my opinion. I hope you can revert back to the old way or at least make it hide to system tray..

**Comment by ResetXPDR** [comment]
I've had many users confused about the app hiding in the system tray and just two who would prefer it.  In any case, it's too late now as I have taken all Systray code out of my app and I am not going to put it back in.

As such your choices are:

1. Use my old [MSFS2020_AutoFPS](https://github.com/ResetXPDR/MSFS2020_AutoFPS) for MSFS 2020 and kayjay's [MSFS2024_AutoFPS](https://github.com/kayjay1c6b/MSFS2024_AutoFPS-by-kayJay_1c6) for MSFS 2024, both of which still use the system tray icon method you like.
2. Use this app and the freeware app https://www.4t-niagara.com/tray.html to have the icon go to the system tray as you desire.

**Comment by Jmknights93** [comment]
That's a real shame. Is there any way I can go back to v0.4.4.0 as I don't use MS24 right now.

**Comment by ResetXPDR** [comment]
Just keep using MSFS2020_AUTOFPS like I mentioned above.

**Comment by Jmknights93** [comment]
Download link on **MSFS2020_AUTOFPS** release page refers me to "v0.4.4.1 MSFS 2024 1.2.8.0 Compatibility Update". So if you would kindly upload v0.4.4.0 I'll stay on that for now. Many thanks.

**Comment by ResetXPDR** [comment]
This one, which is functionally equivalent to 0.4,4.0 for MSFS 2020 and has the systray icon, is the one to use https://github.com/ResetXPDR/MSFS2020_AutoFPS/releases/download/v0.4.3.1/MSFS_AutoFPS-installer-v0.4.3.1.exe

**Comment by ResetXPDR** [comment]
Please try out the latest test build (12 or later), which has reintroduced the app closing to the system tray as an icon as an install option and let me know if that satisfies your request. https://github.com/ResetXPDR/MSFS_AutoFPS/releases/tag/v0.4.4.2-test
