### ISSUE TITLE
MSFS2024 Clouds being set to LOW.

### ISSUE THREAD

**Issue by Dazzlercee** [ResetXPDR/MSFS_AutoFPS#12]
The cloud setting in the MSFS2024 is changing to LOW even though DECREASE CLOUD QUALITY is unticked.

**Comment by ResetXPDR** [comment]
Can you send your log file please. It is located in %appdata%\MSFS_AutoFPS\log

**Comment by Dazzlercee** [comment]
Log file attached.

regards,
Daz


________________________________

**Comment by ResetXPDR** [comment]
There is no file attached. Please try again.

**Comment by Dazzlercee** [comment]
Hi,

A bit more info; I was experiencing CTDs after the upgrade to latest version so I uninstalled/reinstalled to reset config and then set IFR as required. I unticked DCQ but noticed during a flight the clouds looked awful, so I checked the in-sim settings and they were on LOW. I manually set them back to ULTRA but on the next flight they reverted to LOW again.

Regards,
Daz

________________________________

**Comment by ResetXPDR** [comment]
If you want to change the in sim settings you need to NOT be running MSFS_AutoFPS at the time. Try changing your MSFS settings without MSFS_AutoFPS running then see how it behaves when AutoFPS is run again.

Send me the log file if still not playing the game, but I reckon that's it.

**Comment by gvert27** [comment]
I am having the same issue with Clouds being descreased to Low, without the option ticked.

> If you want to change the in sim settings you need to NOT be running MSFS_AutoFPS at the time. Try changing your MSFS settings without MSFS_AutoFPS running then see how it behaves when AutoFPS is run again.
> 
> Send me the log file if still not playing the game, but I reckon that's it.

Followed exactly this and it changed to Low on the next start.

[MSFS_AutoFPS20241222.log](https://github.com/user-attachments/files/18221615/MSFS_AutoFPS20241222.log)

**Comment by ResetXPDR** [comment]
Now we are getting somewhere. It looks like your app config file has become corrupt. Try a clean install of this app by running the app installer, select the Remove button, close then run the installer again and click Install.

Let me know how that goes.

**Comment by ResetXPDR** [comment]
These will be the offending lines in your config file, if you haven't removed the app already:

  <add key="defaultTLOD" value="NaN" />
  <add key="defaultTLOD_VR" value="NaN" />
  <add key="defaultOLOD" value="NaN" />
  <add key="defaultOLOD_VR" value="NaN" />
  <add key="defaultCloudQ" value="0" />
  <add key="defaultCloudQ_VR" value="1" />
  <add key="defaultDynSet" value="false" />
  <add key="defaultDynSetVR" value="false" />

Removing the app and reinstalling will get rid of these lines and you should be good to go.

**Comment by gvert27** [comment]
Roger, will check it as soon as possible :)

**Comment by gvert27** [comment]
> Now we are getting somewhere. It looks like your app config file has become corrupt. Try a clean install of this app by running the app installer, select the Remove button, close then run the installer again and click Install.
> 
> Let me know how that goes.

Removing and reinstalling fixed it 👍

**Comment by ResetXPDR** [comment]
Awesome! Thanks for the feedback.
