### ISSUE TITLE
Frame Generation not recognized anymore

### ISSUE THREAD

**Issue by TheFlyingDutchman77** [ResetXPDR/MSFS_AutoFPS#13]
Thx for your great piece of software. It seems that with 0.4.4 frame generation active in MSFS2024 is not being recognized anymore. It would be nice if that could be fixed! 

![image](https://github.com/user-attachments/assets/653e9f11-ded2-4900-8c2b-83eebcca568d)

**Comment by fliegeroli** [comment]
Nimm die neue, aktualisierte Version 0.4.4.1...

**Comment by TheFlyingDutchman77** [comment]
I can confirm that in version 0.4.4.1 this is fixed indeed. Issue can be closed.
