### ISSUE TITLE
Unable to run in the background

### ISSUE THREAD

**Issue by educanedo03** [ResetXPDR/MSFS_AutoFPS#14]
Hi, I´ve been using auto fps for a long time and I love it. with the recent update I´ve found a problem that may no bother everyone but I find it quite annoying, now with the new update I cant minimize to the system tray the app and it stays as an open window. I hope it can get fixed.

**Comment by ResetXPDR** [comment]
I may reintroduce that in a later version, but not right now as it would conflict with the new way it works and I now get far less support questions than I used to because I changed it that way.

**Comment by educanedo03** [comment]
Is there any way that I could go back to the msfs2020 only version??

**Comment by ResetXPDR** [comment]
Again this is covered in the readme FAQ. You can download the last version from here https://github.com/ResetXPDR/MSFS2020_AutoFPS/releases/tag/v0.4.3.1

**Comment by ResetXPDR** [comment]
Please try out the latest test build (12 or later), which has reintroduced the app closing to the system tray as an icon as an install option. https://github.com/ResetXPDR/MSFS_AutoFPS/releases/tag/v0.4.4.2-test

**Comment by Jmknights93** [comment]
Thank you, this seems to work perfectly.
