### ISSUE TITLE
Problem with installer

### ISSUE THREAD

**Issue by FlyingOtter19** [ResetXPDR/MSFS_AutoFPS#15]
When I run the .exe of 0.4.4.1 update, the app get stuck on "deleting old MSFS_AutoFPS Version...".
I already tried to remove it, by the installer, but it send me the following error message : Exception "System.IO.IOException" during Uninstall. I tried to install the 0.4.3.1 version, I can uninstall it, but then when I launch the 0.4.4.1 version it only says "Update" or "Remove" with the problems I mentionned earlier.

**Comment by ResetXPDR** [comment]
Is the error message more descriptive than that? If so, can you please advise the full error message.

When you say you are uninstalling 0.4.3.1, are you uninstalling it using the installer and the Remove option? This is the way it should be done.

If the 0.4.4.1 installer is still giving you an Update option after uninstalling 0.4.3.1 then the latter mustn't have uninstalled correctly.  Try going into the %appdata%\MSFS2020_AutoFPS\ directory and delete everything in there then try the MSFS_AutoFPS installer again.

Actually, I'd rather you try the 0.4.4.2-test version, currently test 10, as I have updated the installer in that and it is a more robust version anyway. You can get it here https://github.com/ResetXPDR/MSFS_AutoFPS/releases/tag/v0.4.4.2-test

**Comment by FlyingOtter19** [comment]
Ok, did as you said and the installation worked!
There was no much more info on the error windows box.
