### ISSUE TITLE
Transparenz

### ISSUE THREAD

**Issue by fliegeroli** [ResetXPDR/MSFS_AutoFPS#18]
Hi. This is not a problem, but I can't find a button where I can send you a message. Really great program. Small question. Can you perhaps create a transparency with a kind of slider or just make the values ​​there? Best wishes, Oliver

**Comment by ResetXPDR** [comment]
Thank you. I experimented with transparency a few months ago and it was going to be too complex with other UI colouring, so instead I went for a collapsible UI which is described here:

- The user can progressively hide parts of the UI when the app window is double clicked anywhere that is not a control. The first double click will hide the expert settings section (if applicable), the second will hide the general settings section and a third double click will restore all hidden settings sections. The last state in use will be restored when next starting the app.

I use it this way all the time eg. these are my actual settings:
![image](https://github.com/user-attachments/assets/d9eaf550-2fb8-4b3f-a8a4-fb9d5315a82a)
but I collapse it down to this while flying:
![image](https://github.com/user-attachments/assets/77bacb57-0e25-45b4-afe2-a5d1853d3a73)
