### ISSUE TITLE
Connection Status

### ISSUE THREAD

**Issue by lewakon** [ResetXPDR/MSFS_AutoFPS#3]
SimConnect and session connection status remain red, regardless of whether I start the app before launching MSFS or while in the menus. Is there something I might be overlooking or missing in the setup?

**Comment by ResetXPDR** [comment]
Did you do this from the readme on installation?

- If after installing and running the app your simconnect always stays red:
  - Try downloading and installing a Microsoft official version of “Microsoft Visual C++ 2015 - 2022 Redistributable”, which may be missing from your Windows installation.
  - If still not resolved and the error code in your AutoFPS log file is Exception 31, you most likely have a corrupt MSFS installation so you can choose to either not run this app or to reinstall MSFS completely.

**Comment by ResetXPDR** [comment]
No response for over a day so I assume you fixed it, hence this issue is considered closed.

**Comment by Covee23** [comment]
I am having the same problem . I tried the things you suggested. I also re installed the sim and no luck.

**Comment by ResetXPDR** [comment]
Can you send me your log file please. It is located in %appdata%\MSFS_AutoFPS\log

**Comment by Covee23** [comment]
[MSFS_AutoFPS20241219.log](https://github.com/user-attachments/files/18206324/MSFS_AutoFPS20241219.log)

**Comment by ResetXPDR** [comment]
Thanks. What MSFS version and source (eg. MSFS 2024 Steam version) were you using when this log file was made?

**Comment by Covee23** [comment]
yeah its MSFS 2024 Steam Version.

**Comment by ResetXPDR** [comment]
The bad news is that if you have installed those two Microsoft Visual C++ 2015 - 2022 Redistributable files and you have reinstalled MSFS 2024 and you are still getting Exception 31 error messages in your log file, we are in uncharted territory!

Have you tried it with an empty community folder other than the mobiflight-event-module installed by this app's installer?

**Comment by Covee23** [comment]
No I have not. And yes I feel like it's something on my end due to the vast majority of people are able to use this app. I will try a few more things in the next coming days and let you know how it goes.

**Comment by ResetXPDR** [comment]
I'm just googling this error for more possible solutions.

One suggestion that got someone up running in the past was to run the .NET framework repair tool, which you can download here https://www.microsoft.com/en-us/download/details.aspx?id=30135

**Comment by Covee23** [comment]
Okay I'll try that. I am not at my PC right now but I will try it tomorrow. Thanks

**Comment by ResetXPDR** [comment]
Also, something I experienced myself, is that when you uninstall MSFS 2024 to then reinstall, it doesn't clear out your Steam install files properly. 

I suggest you follow the Steam reinstall instructions from MS found here https://flightsimulator.zendesk.com/hc/en-us/articles/17335196046108-How-to-clean-install-the-simulator-on-PC and try again. 

Unlike MSFS 2020, it only takes around 15 minutes to completely reinstall MSFS 2024, and you don't lose your settings, controller assignments, career or profile, so it is definitely worth a shot.

Let me know how you go when you can get to it.

**Comment by ResetXPDR** [comment]
I'd try the clean install first, then the .net repair tool second if that doesn't do it.

**Comment by Covee23** [comment]
Okay so another fresh install of MSFS and a re install of Auto fps and everything seems to be working now as it should. Thank you for your help.

**Comment by ResetXPDR** [comment]
Awesome. I'm glad you got it working!
