### ISSUE TITLE
app does not detect correct 'FG FPS' when FG (FG mod on 3070) is enabled in MSFS

### ISSUE THREAD

**Issue by Fafhrd67** [ResetXPDR/MSFS_AutoFPS#4]
Although Frame Generation is enabled in MSFS graphics settings, AutoFPS status does not switch to 'FG Active' but always shows up 'PC DX12'.
I have applied all recommendations regarding FG in FAQ page with no results. Moreover, TLOD or OLOD values displayed are always 0.
Any clue on how to troubleshoot this issue ?

**Comment by ResetXPDR** [comment]
Can you please post your log file, which is located in %appdata%\MSFS_AutoFPS\log

**Comment by ResetXPDR** [comment]
Also, check this resolved issue out https://github.com/ResetXPDR/MSFS_AutoFPS/issues/1 and see if it resolves it for you.

**Comment by Fafhrd67** [comment]
Here is the log file..

[MSFS_AutoFPS20241218.log](https://github.com/user-attachments/files/18194806/MSFS_AutoFPS20241218.log)

**Comment by ResetXPDR** [comment]
You have closed this as completed but your log file looks like you have an issue with GPU-Z. If you still want me to look into your original issue or this new one, I will reopen it and take a look.

**Comment by Fafhrd67** [comment]
Sorry, no intention to close this thread. OK if you want to investigate further. Thanks!

**Comment by ResetXPDR** [comment]
OK, going to bed now. I will look at it tomorrow. 

BTW did you check out issue https://github.com/ResetXPDR/MSFS_AutoFPS/issues/1 as I suggested above? And what version of MSFS do you have MS Store or Steam?

**Comment by Fafhrd67** [comment]
Hope you've spent a good night!
I checked out the #1 issue, but found no clue to my problem.
Before I submitted this support ticket, I have also fully unisnstalled AutoFPS and reinstalled for MSFS2024, without improvement on my issue.
I have the MS Store version installed in default directory, and Packages/Community folders on another drive.
Installed MSFS2024 version is 1.2.7.0
Attached is my UserCfg.opt file.
I own GPU-Z, but don't run it while MSFS is active.
Hope that helps.

[UserCfg.zip](https://github.com/user-attachments/files/18197915/UserCfg.zip)

![Capture d'écran 2024-12-19 135208](https://github.com/user-attachments/assets/e74e61c5-b701-4fb1-a9e2-edd6bd869b30)

**Comment by ResetXPDR** [comment]
I can reproduce the issue if I rename the file GpuzShMem.x64.dll in the bin directory to something else, suggesting you do not have all required files in your bin directory. It should look something like this with 19 files:

![397105046-93e9fe1a-1879-4c47-998c-52986649cc3e](https://github.com/user-attachments/assets/019195db-2828-4b48-9306-59b9b28cea97)

The installer should have put all the required files there. Nonetheless, you can manually place all the files there yourself, just download https://github.com/ResetXPDR/MSFS_AutoFPS/blob/main/MSFS_AutoFPS.zip and extract all file to the bin directory here %appdata%\MSFS_AutoFPS\bin and see if that now works.

**Comment by Fafhrd67** [comment]
Hello,
I have doublechecked the contents of the bin directory. All 19 files matched the list and zip file that you have sent. 
I have replaced the bin directory content with the 19 files that you sent me.
The result remains the same : FG not detected , TLOD and OLOD= 0 and log file error
Critical Exception occurred: MSFS_AutoFPS - Unable to load DLL 'GpuzShMem.x64.dll' or one of its dependencies: Le module spécifié est introuvable. (0x8007007E) 
This is very weird, isn't it?

**Comment by ResetXPDR** [comment]
Yes very weird. It's possibly a permissions issue, although you are usually fine in your roaming directory, or your AV program blocking it. For the former, maybe try running the app as admin. For the latter, try temporarily disabling your AV program and if it then works set an exclusion in your AV program for this app. 

BTW, you keep closing this issue, by accident I expect? If so, when you reply click on comment not close with comment.

**Comment by ResetXPDR** [comment]
BTW, copilot suggests the following addition thing to try for this specific issue:

- File Permissions: The user might not have the necessary permissions to access the DLL file. Ensuring the user has read/write access to the directory might help

**Comment by ResetXPDR** [comment]
I know you have tried some of the following, but perhaps you did not do a full clean removal of each of them.

Try a clean install of the new app version just released today here https://github.com/ResetXPDR/MSFS_AutoFPS/releases/tag/v0.4.4.1 by running the app installer, select the Remove button, close then run the installer again and click Install.

Also try a clean reinstall, not just an uninstall/reinstall, of MSFS 2024 as outlined for your MSFS version [here](https://flightsimulator.zendesk.com/hc/en-us/articles/17335196046108-How-to-clean-install-the-simulator-on-PC), which only takes around 15 minutes to complete and all your settings, controller assignments, career progression and your pilot profile are retained.

Finall, if all else fails, try manually installing:
- https://aka.ms/vs/17/release/vc_redist.x86.exe
- https://aka.ms/vs/17/release/vc_redist.x64.exe
- https://dotnet.microsoft.com/en-us/download/dotnet/7.0

**Comment by Fafhrd67** [comment]
I already had an improvement yesterday by updating the VC and dotnet libraries (file GpuzShMem.x64.dll OK).
Today everything's fine thanks to your last valuable advices.
Thanks again for your help and implication, greatly appeciated !
JM

**Comment by ResetXPDR** [comment]
Awesome. We got there in the end!
