### ISSUE TITLE
too low TLOD

### ISSUE THREAD

**Issue by AndyCYXU** [ResetXPDR/MSFS_AutoFPS#8]
Hi, is it possible so that LOW TLOD (below 100) is only below certain altitude.. for example below 500 AGL, go ahead and lower TLOD to 25 if must be so at low altitude, but from 500+ AGL, keep it at minimum 100-TLOD (or whatever user chooses).

I was coming for an approach and it just looks horrible below TLOD-100 while i was still at 2000AGL +, i had to change the minimum to 100-TLOD and it was nice and performance was still fine, but when i land i do not mind it going down to 25 or from 500-AGL where I no longer pay attention to scenery and do not mind having low TLOD as i concentrate on the final and my field of view is also smaller at 500 AGL so i really would not notice it.
I see there different options in Expert mode but as i understand them they are not for what I am asking, more like below X will always be tlod=x, but once above that it is up to the program

Thanks

**Comment by AndyCYXU** [comment]
Ok, thanks I will try that, I was kind of confused by what this 5000 (default) was there for, it might work as i want it to as you explain, I was not understanding what this option was, so this : 

1 Alt TLOD Base = below 100ft TOLD will be 25
2 Alt TLOD Top =  above this altitude (1000ft) TLOD will be 100 or grater (like in this example) 

 so between 100ft and 1000ft TLOD will be adjusted to maintain performance, so it can go from 25-100

hopefully I am getting this right,
thank you

**Comment by ResetXPDR** [comment]
You got most of it right. The only thing to correct is that TLOD will change proportionally, not based on performance, between 100 and 1000 ft.  eg. at half way up that range (ie. 550 ft) the TLOD will be half way between 25 and 100 (ie. 62.5). AutoTLOD does not care about FPS (well unless you tick one option but we won't go there), it is based on a simple formula.

**Comment by ResetXPDR** [comment]
I'll close this as I believe I have answered your query.
