### ISSUE TITLE
Latest FS2024 Patch  1.2.8.0 Broke Compatibility

### ISSUE THREAD

**Issue by emmanuelgemini** [ResetXPDR/MSFS_AutoFPS#9]
Installed the latest patch  1.2.8.0. Booted the sim and loaded a flight I noticed it was blurry, checked the settings, TLOD was at 10 while auto-fps shows 200. 

Tried flipping between 10-400 inside auto-fps, no visual change. Changing from in-game settings does.

Another thing that hinted to me that it became incompatible is that auto-fps is incorrectly detecting/displaying the current cloud settings. I have it on Ultra, auto-fps is showing low (GPU usage 40%)

**Comment by Burnhaven** [comment]
same here   
![image](https://github.com/user-attachments/assets/8ead758c-40fb-42f0-bdf8-5f08946202ee)

**Comment by DivineStag** [comment]
Also having similar issues. Doesnt seem to be detecting my frame gen FPS but was working fine before the update. Thinks my FPS is low so is putting my LOD low but FPS in sim is above what I have set

**Comment by ResetXPDR** [comment]
I am aware of this issue and have been working on a fix.
Can you guys please try this and let me know if it fixes it for you. 

https://github.com/ResetXPDR/MSFS_AutoFPS/releases/download/v0.4.4.1-RC/MSFS_AutoFPS-installer-v0.4.4.1-RC2.exe

**Comment by DivineStag** [comment]
Seems to be good, thanks for the extremely fast response! Keep up the good work

**Comment by ResetXPDR** [comment]
I've had confirmation from others that it is now working. Thanks for letting me know. A formal release update has just been posted.

**Comment by Burnhaven** [comment]
Neither the RC version or the latest version worked for me The TLOD and
OLOD I think read not applicable this time and the simulator locked up as
soon as I got into an aircraft and I repeated that to verify.. I've now
uninstalled auto FPS and will try the simulator again.

**Comment by Burnhaven** [comment]
With the latest version of Auto FPS uninstalled the simulator launched
normally after a reboot... I'll reinstall the app and try it again in the
morning

**Comment by emmanuelgemini** [comment]
Hmmm very strange. The RC worked for me earlier, then updated to the official release and then it stopped working. I now rolled back to RC2, and now that's not working as well. 

hmmm... I'll try a clean install see if that helps.

**Comment by emmanuelgemini** [comment]
Alright, completed a clean install. That fixed it for me. Working again now.

**Comment by Burnhaven** [comment]
Yes after clean re-install it's working correctly now.
thanks!

Randy
